sudo: false
language: cpp
addons:
  apt:
    sources:
    - llvm-toolchain-precise
    - ubuntu-toolchain-r-test
    packages:
    - clang-3.7
    - g++-5
    - gcc-5
script:
- mkdir -p build
- cd build
- cmake ..
- cmake --build . --config Release
- ctest --config Release --output-on-failure
env:
- MY_CXX=g++-5
- MY_CXX=clang++
install:
- export CXX="${MY_CXX}"
